build_from:
  aarch64: couchdb:3.3
  amd64: couchdb:3.3
  armv7: couchdb:3.3
args:
  BUILD_ARCH: "{arch}"
  BUILD_DATE: "{date}"
  BUILD_DESCRIPTION: "CouchDB server for Obsidian LiveSync"
  BUILD_NAME: "LiveSync CouchDB"
  BUILD_REF: "{ref}"
  BUILD_REPOSITORY: "{repository}"
  BUILD_VERSION: "{version}"
